# Generated by Django 3.0.6 on 2020-05-21 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpis',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='wpis',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
